emulator_task:
  name: Integration Tests (x86)
  container:
    image: cirrusci/android-sdk:30
    kvm: true
    cpu: 8
    memory: 12G

  # TODO: add background
  # Start node setup as early as possible
  setup_node_script:
    - wget https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.15.1-deb-1nodesource1_amd64.deb
    - sudo dpkg -i nodejs_16.15.1-deb-1nodesource1_amd64.deb
    - npm install
    - which node
    - touch /tmp/node_setup_finished
  accel_check_script: emulator -accel-check
  setup_emulator_script:
    - sdkmanager --update
    - sdkmanager "system-images;android-30;google_apis_playstore;x86"
    - echo no | avdmanager create avd --force --name "api-30" --abi "google_apis_playstore/x86" --package "system-images;android-30;google_apis_playstore;x86"
  start_emulator_background_script:
    # start adb already otherwise the next step sometimes hangs
    - adb devices
    - emulator -avd "api-30" -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -accel on
  wait_for_emu_and_disable_animations_script:
    # https://android.stackexchange.com/a/83747/374266
    - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done; input keyevent 82'
    # I have chained those commands because often the animation setting would fail with "no devices/emulators found"
    - adb shell settings put global window_animation_scale 0.0
    - adb shell settings put global transition_animation_scale 0.0
    - adb shell settings put global animator_duration_scale 0.0
  wait_for_node_setup_to_finish_script:
    - while [ ! -f /tmp/node_setup_finished ]; do sleep 5; done
