macos_instance:
  #    image: cirrusci/android-sdk:29
  image: ghcr.io/cirruslabs/macos-monterey-base:latest
  kvm: true
  cpu: 12
  memory: 12G

task:
  env:
    ANDROID_SDK_ROOT: ${HOME}/cmdline-tools
    PATH: ${ANDROID_SDK_ROOT}/platform-tools:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/tools/bin:${PATH}
  setup_brew_script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - brew tap homebrew/cask
    - brew tap homebrew/cask-versions
  install_java_script:
    - brew install java8
    - brew install openjdk@11
    - - sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
  install_android_sdk_script:
    - wget -q https://dl.google.com/android/repository/commandlinetools-mac-8512546_latest.zip
    - unzip -q commandlinetools-mac-8512546_latest.zip
    - (yes || true) | cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses > /dev/null
    - cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator" "system-images;android-30;google_apis;arm64-v8a"
  create_device_script:
    echo no | avdmanager create avd --force --name "api-30" --abi "google_apis_playstore/arm64-v8a" --package "system-images;android-30;google_apis_playstore;arm64-v8a"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator -avd "api-30" -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
#  assemble_instrumented_tests_script:
#    ./android/gradlew -p android :app:assembleE2eRelease
  wait_for_emulator_script:
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  disable_animations_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
#  run_instrumented_tests_script:
#    ./gradlew connectedDebugAndroidTest
