macos_instance:
  #    image: cirrusci/android-sdk:29
  image: ghcr.io/cirruslabs/macos-monterey-base:latest
  kvm: true
  cpu: 12
  memory: 12G

task:
  setup_brew_script: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew tap homebrew/cask
  install_java_script: brew install openjdk@11
  install_android_sdk_script: brew install --cask android-sdk
  accept_android_sdk_licenses_script: yes | sdkmanager --licenses
  install_android_sdk_components_script: sdkmanager --install "build-tools;30.0.3" "platform-tools" "platforms;android-30"
  install_android_sdk_emulator_script: sdkmanager --install "emulator"
  install_android_sdk_system_images_script: sdkmanager --install "system-images;android-30;google_apis;arm64_v8a"
  accel_check_script: emulator -accel-check

#  create_device_script:
#    echo no | avdmanager create avd --force --name "api-29" --abi "google_apis_playstore/x86" --package "system-images;android-29;google_apis_playstore;x86"
#  start_emulator_background_script:
#    $ANDROID_HOME/emulator/emulator -avd "api-29" -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
#  assemble_instrumented_tests_script:
#    ./android/gradlew -p android :app:assembleE2eRelease
#  wait_for_emulator_script:
#    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
#  disable_animations_script: |
#    adb shell settings put global window_animation_scale 0.0
#    adb shell settings put global transition_animation_scale 0.0
#    adb shell settings put global animator_duration_scale 0.0
#  run_instrumented_tests_script:
#    ./gradlew connectedDebugAndroidTest
