name: Set up Node
description: Set up Node

runs:
  using: composite
  steps:
    # Version: 3.0.2
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0

    - uses: actions/setup-node@09ba51f18e18a3756fea1f54d09c6745c064491d
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install node packages
      uses: nick-invision/retry@7c68161adf97a48beb850a595b8784ec57a98cbb
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: npm ci
