home:
  href: home
  title: Welcome to the New Expensify!

# Hubs are comprised of sections and articles. Sections contain multiple related articles, but there can be standalone articles as well
hubs:
  - href: send-money
    title: Send money
    description: With only a couple of clicks, send money to your friends or coworkers using NewExpensify.
    sections:
      - href: workspaces
        title: Workspaces
        articles:
          - href: The-Free-Plan
            title: The Free Plan

  - href: request-money
    title: Request money
    description: Request money for work expenses, bills, or a night out with friends using NewExpensify.

  - href: other
    title: Other
    description: Everything else you're looking for is right here.
    articles:
      - href: Account-Management
        title: Account Management
