name: 'Contributor Checklist Test'
description: 'Verifies that both PR checklists are filled out'
inputs:
  GITHUB_TOKEN:
    description: Auth token for New Expensify Github
    required: true
runs:
  using: 'node12'
  main: './index.js'
