name: PR Author Checklist

on: pull_request

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: authorChecklist.js
        uses: Expensify/App/.github/actions/javascript/authorChecklist@tgolen-github-action-new-checklist
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
