name: PR Author Checklist

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: authorChecklist.js
        uses: Expensify/App/.github/actions/javascript/authorChecklist@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
