name: PR Author Checklist

on: pull_request

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: authorChecklist.js
        uses: Expensify/App/.github/actions/javascript/authorChecklist@53a2907afbcee71a4842e5d1ae5093085456fef9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
