name: PR Author Checklist

on: pull_request

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: authorChecklist.js
        uses: Expensify/App/.github/actions/javascript/authorChecklist@b383bc493b7c927d93617c3ce76c2d719ba8e858
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
