name: Contributor+ Checklist

on: pull_request_review

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify' && (github.event_name == 'pull_request_review' && contains(github.event.review.body, '- ['))
    steps:
      - name: contributorChecklist.js
        uses: Expensify/App/.github/actions/javascript/contributorChecklist@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECKLIST: 'contributorPlus'
