name: PR Reviewer Checklist

on: pull_request_review

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: reviewerChecklist.js
        uses: Expensify/App/.github/actions/javascript/reviewerChecklist@b383bc493b7c927d93617c3ce76c2d719ba8e858
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
