name: Contributor Checklist

on:
  pull_request_comment:
  pull_request_review_comment:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: contributorChecklist.js
        uses: Expensify/App/.github/actions/javascript/contributorChecklist@andrew-checklist
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
