name: "Contributor Checklist"

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: contributorChecklist.js
        uses: Expensify/App/.github/actions/javascript/contributorChecklist@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
