name: Contributor Checklist

on:
  issue_comment:
  pull_request_review_comment:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, '- [x]') || github.event_name == 'pull_request_review_comment' && contains(github.event.pull_request_review_comment.body, '- [x]') || github.event_name == 'pull_request' && contains(github.event.pull_request.body, '- [x]') }}
    steps:
      - name: contributorChecklist.js
        uses: Expensify/App/.github/actions/javascript/contributorChecklist@andrew-checklist
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
