name: Verify Podfile

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]

jobs:
  verify:
    if: github.actor != 'OSBotify'
    runs-on: ubuntu-latest
    steps:
      - uses: Expensify/App/.github/actions/composite/setupNode@andrew-npm-8

      - run: ./.github/scripts/verifyPodfile.sh
